version: '3.8'

services:
  sentinelheaders-web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./logs:/app/logs
    networks:
      - sentinelheaders-network

  # Optional: Add MongoDB for future features
  # mongodb:
  #   image: mongo:6
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   volumes:
  #     - mongodb_data:/data/db
  #   networks:
  #     - sentinelheaders-network

networks:
  sentinelheaders-network:
    driver: bridge

# volumes:
#   mongodb_data: